num_classes: 5
ignore_index: 255
num_classes_binned: 4

classes:
  0:
    name: drivable
    color: "#22c55e"
  1:
    name: terrain_nondrivable
    color: "#a16207"
  2:
    name: static_obstacle
    color: "#ef4444"
  3:
    name: dynamic_vehicle
    color: "#f97316"
  4:
    name: dynamic_pedestrian
    color: "#3b82f6"

bin_5_to_4:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 3

binned_classes:
  0:
    name: drivable
    color: "#22c55e"
  1:
    name: terrain_nondrivable
    color: "#a16207"
  2:
    name: static_obstacle
    color: "#ef4444"
  3:
    name: dynamic_object
    color: "#3b82f6"

semantic_kitti_5class:
  0: 255
  1: 255
  10: 3
  11: 4
  13: 3
  15: 3
  16: 3
  18: 3
  19: 3
  20: 3
  30: 4
  31: 4
  32: 4
  40: 0
  44: 0
  48: 1
  49: 1
  50: 2
  51: 2
  52: 2
  60: 0
  70: 1
  71: 1
  72: 1
  80: 2
  81: 2
  99: 2
  254: 3
  255: 4
